# Список хостов и маршрутов
hosts:
  - host: dotops.ru
    routes:
      - name: dotops-lending
        path: /
        service:
          name: dotops-lending
          namespace: dotops-lending
          port: 80

# Gateway конфигурация
gateway:
  className: envoy
  namespace: envoy-gateway-system
  name: envoy-gateway
  tlsSecretName: envoy-domains-cert

# Cert-Manager конфигурация
certManager:
  enabled: true
  email: vlad.kanatik@icloud.com